In [98]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import seaborn as sns

In [99]:
!pip install seaborn


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
data={ 'ColA':['2','3','4'],
      'ColB':['3','6','7'],
      'Col3':[1,2,3]}
df=pd.DataFrame(data)
print(df.dtypes)
df=df.astype({'ColA':'int64',
          'ColB':'int64'})
df.dtypes

ColA    object
ColB    object
Col3     int64
dtype: object


ColA    int64
ColB    int64
Col3    int64
dtype: object

In [17]:
data={ 'ColA':['2','3','4',np.nan],
      'ColB':['3','6','7','8'],
      'Col3':[1,2,3,None]}
df=pd.DataFrame(data)
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ColA    3 non-null      object 
 1   ColB    4 non-null      object 
 2   Col3    3 non-null      float64
dtypes: float64(1), object(2)
memory usage: 224.0+ bytes


ColA ColB  Col3
0    2    3   1.0
1    3    6   2.0
2    4    7   3.0
3  NaN    8   NaN

In [16]:
df.isnull()

ColA   ColB   Col3
0  False  False  False
1  False  False  False
2  False  False  False
3   True  False   True

In [18]:
df.isna()

ColA   ColB   Col3
0  False  False  False
1  False  False  False
2  False  False  False
3   True  False   True

In [19]:
df.notnull()

ColA  ColB   Col3
0   True  True   True
1   True  True   True
2   True  True   True
3  False  True  False

In [21]:
df.isnull().mean()*100


ColA    25.0
ColB     0.0
Col3    25.0
dtype: float64

In [22]:
data={ 'ColA':['2','3','4',np.nan],
      'ColB':['3','6','7','8'],
      'Col3':[1,2,3,None]}
df=pd.DataFrame(data)
cons=0
df.fillna(0)

ColA ColB  Col3
0    2    3   1.0
1    3    6   2.0
2    4    7   3.0
3    0    8   0.0

In [25]:
df.dtypes

ColA     object
ColB     object
Col3    float64
dtype: object

In [34]:
import pandas as pd
import numpy as np

# Define the data dictionary
data = {
    'ColA': ['2', '3', '4', np.nan],   # '2', '3', '4' are strings
    'ColB': ['3', '6', '7', '8'],      # All values are strings
    'Col3': [1, 2, 3, None]            # Mixed types with None (Pythonic NaN)
}

# Create DataFrame
df = pd.DataFrame(data)

# Convert columns to numeric (handling errors due to NaNs)
df['ColA'] = pd.to_numeric(df['ColA'], errors='coerce')  # Convert to numeric (int/float), NaN remains
df['ColB'] = pd.to_numeric(df['ColB'])  # No NaNs here, conversion succeeds
df['Col3'] = pd.to_numeric(df['Col3'])  # Convert column to numeric

# Calculate mean values, ignoring NaNs
CA = df['ColA'].mean()
C3 = df['Col3'].mean()

# Fill missing values
df['ColA'].fillna(CA, inplace=True)
df['Col3'].fillna(C3, inplace=True)

# Convert to int if no missing values remain
df = df.astype({'ColA': 'int64', 'ColB': 'int64', 'Col3': 'int64'})

print(df)



   ColA  ColB  Col3
0     2     3     1
1     3     6     2
2     4     7     3
3     3     8     2


C:\Users\DELL\AppData\Local\Temp\ipykernel_21416\2526106051.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ColA'].fillna(CA, inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_21416\2526106051.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when do

In [40]:
import pandas as pd
import numpy as np

# Define the data dictionary
data = {
    'ColA': ['2', '3', '4', np.nan],   # '2', '3', '4' are strings
    'ColB': ['3', '6', '7', '8'],      # All values are strings
    'Col3': [1, 2, 3, None]            # Mixed types with None (Pythonic NaN)
}

# Create DataFrame
df = pd.DataFrame(data)
df
df['ColA']=pd.to_numeric(df['ColA'])
df['ColB']=pd.to_numeric(df['ColB'])
df['Col3']=pd.to_numeric(df['Col3'])

ca=df['ColA'].median()
cc=df['Col3'].median()

df['ColA'].fillna(ca,inplace=True)
df['Col3'].fillna(cc,inplace=True)
df


C:\Users\DELL\AppData\Local\Temp\ipykernel_21416\2894547031.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ColA'].fillna(ca,inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_21416\2894547031.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doi

ColA  ColB  Col3
0   2.0     3   1.0
1   3.0     6   2.0
2   4.0     7   3.0
3   3.0     8   2.0

In [43]:
import pandas as pd
import numpy as np

# Define the data dictionary
data = {
    'ColA': ['2', '4', '4', np.nan],   # '2', '3', '4' are strings
    'ColB': ['3', '6', '7', '8'],      # All values are strings
    'Col3': [1, 2, 3, None]            # Mixed types with None (Pythonic NaN)
}

# Create DataFrame
df = pd.DataFrame(data)
df

CA=df['ColA'].mode()[0]
df['ColA'].fillna(CA)

0    2
1    4
2    4
3    4
Name: ColA, dtype: object

In [46]:
import pandas as pd
import numpy as np

# Define the data dictionary
data = {
    'ColA': ['2', '4', '4', np.nan],   # '2', '3', '4' are strings
    'ColB': ['3', '6', '7', '8'],      # All values are strings
    'Col3': [1, 2, 3, None]            # Mixed types with None (Pythonic NaN)
}

# Create DataFrame
df = pd.DataFrame(data)
print(df)

df.dropna()

  ColA ColB  Col3
0    2    3   1.0
1    4    6   2.0
2    4    7   3.0
3  NaN    8   NaN


ColA ColB  Col3
0    2    3   1.0
1    4    6   2.0
2    4    7   3.0

In [47]:
import pandas as pd
import numpy as np

# Define the data dictionary
data = {
    'ColA': ['2', '4', '4', np.nan],   # '2', '3', '4' are strings
    'ColB': ['3', '6', '7', '8'],      # All values are strings
    'Col3': [1, 2, 3, None]            # Mixed types with None (Pythonic NaN)
}

# Create DataFrame
df = pd.DataFrame(data)
print(df)

df.dropna(axis=1)

  ColA ColB  Col3
0    2    3   1.0
1    4    6   2.0
2    4    7   3.0
3  NaN    8   NaN


ColB
0    3
1    6
2    7
3    8

In [50]:
import pandas as pd
import numpy as np

# Define the data dictionary
data = {
    'ColA': ['2', '4', '4', np.nan],   # '2', '3', '4' are strings
    'ColB': [None, '6', '7', np.nan],      # All values are strings
    'Col3': [1, 2, 3, None]            # Mixed types with None (Pythonic NaN)
}

# Create DataFrame
df = pd.DataFrame(data)
print(df)

df.dropna(how='all')

  ColA  ColB  Col3
0    2  None   1.0
1    4     6   2.0
2    4     7   3.0
3  NaN   NaN   NaN


ColA  ColB  Col3
0    2  None   1.0
1    4     6   2.0
2    4     7   3.0

In [66]:
import pandas as pd
import numpy as np

# Define the data dictionary
data = {
    'ColA': ['2', '4', '4', '2'],   # '2', '3', '4' are strings
    'ColB': [np.nan, '6', '7', np.nan],      # All values are strings
    'Col3': [1, 2, 3, None]            # Mixed types with None (Pythonic NaN)
}

# Create DataFrame
df = pd.DataFrame(data)
print(df)

df=df.dropna(thresh=2)
print(df)


  ColA ColB  Col3
0    2  NaN   1.0
1    4    6   2.0
2    4    7   3.0
3    2  NaN   NaN
  ColA ColB  Col3
0    2  NaN   1.0
1    4    6   2.0
2    4    7   3.0


In [79]:
import pandas as pd
import numpy as np

# Define the data dictionary
data = {
    'ColA': ['2', '4', '4', '2','2','2'],   # '2', '3', '4' are strings
    'ColB': [np.nan, '6', '6', np.nan,'7','7'],      # All values are strings
    'Col3': [1, 2, 2, None,1,2]            # Mixed types with None (Pythonic NaN)
}
df=pd.DataFrame(data)
print(df)

df=df.drop_duplicates()
df


  ColA ColB  Col3
0    2  NaN   1.0
1    4    6   2.0
2    4    6   2.0
3    2  NaN   NaN
4    2    7   1.0
5    2    7   2.0


ColA ColB  Col3
0    2  NaN   1.0
1    4    6   2.0
3    2  NaN   NaN
4    2    7   1.0
5    2    7   2.0

In [75]:
df

0    False
2     True
dtype: bool

In [83]:
import pandas as pd
import numpy as np

# Define the data dictionary
data = {
    'ColA': ['2', '4', '4', '2','2','2','0'],   # '2', '3', '4' are strings
    'ColB': [np.nan, '6', '6', np.nan,'7','7','8'],      # All values are strings
    'Col3': [1, 2, 3, None,5,None,7]            # Mixed types with None (Pythonic NaN)
}

df=pd.DataFrame(data)
print(df)

df['Col3']=df['Col3'].interpolate()
print(df)

  ColA ColB  Col3
0    2  NaN   1.0
1    4    6   2.0
2    4    6   3.0
3    2  NaN   NaN
4    2    7   5.0
5    2    7   NaN
6    0    8   7.0
  ColA ColB  Col3
0    2  NaN   1.0
1    4    6   2.0
2    4    6   3.0
3    2  NaN   4.0
4    2    7   5.0
5    2    7   6.0
6    0    8   7.0


In [97]:
import pandas as pd
import numpy as np

# Define the data dictionary
data = {
    'ColA': ['2', '4', '4', '2','2'],   # '2', '3', '4' are strings
    'ColB': [np.nan, '6', '6', np.nan,'7'],      # All values are strings
    'Col3': [1, 2, 3, None,5]            # Mixed types with None (Pythonic NaN)
}

df=pd.DataFrame(data)
print(df)

knni=KNNImputer(n_neighbors=2)
new_Data=knni.fit_transform(df)
print('KNN Imputation')
print(new_Data)

lr=IterativeImputer(estimator=LinearRegression())
new_Data=lr.fit_transform(df)
print('Linear Regressor')
print(new_Data)

dt=IterativeImputer(estimator=DecisionTreeRegressor())
new_Data=dt.fit_transform(df)
print('Decision Tree Regressor')
print(new_Data)

rf=IterativeImputer(estimator=RandomForestRegressor(n_estimators=100))
new_Data=rf.fit_transform(df)
print("Random Forest Regressor")
print(new_Data)


  ColA ColB  Col3
0    2  NaN   1.0
1    4    6   2.0
2    4    6   3.0
3    2  NaN   NaN
4    2    7   5.0
KNN Imputation
[[2.  6.  1. ]
 [4.  6.  2. ]
 [4.  6.  3. ]
 [2.  6.5 3. ]
 [2.  7.  5. ]]
Linear Regressor
[[2. 7. 1.]
 [4. 6. 2.]
 [4. 6. 3.]
 [2. 7. 0.]
 [2. 7. 5.]]
Decision Tree Regressor
[[2. 6. 1.]
 [4. 6. 2.]
 [4. 6. 3.]
 [2. 6. 1.]
 [2. 7. 5.]]
Random Forest Regressor
[[2.         6.42       1.        ]
 [4.         6.         2.        ]
 [4.         6.         3.        ]
 [2.         6.42       1.83666667]
 [2.         7.         5.        ]]


C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\impute\_iterative.py:713: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(


In [108]:
df=sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [105]:
df.isnull().mean()*100

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [114]:
df = df.drop(columns=['embark_town'])  # Removes the 'embark_town' column
df= df.drop(columns=['embarked'])
df

survived  pclass     sex   age  sibsp  parch     fare   class    who  \
0           0       3    male  22.0      1      0   7.2500   Third    man   
1           1       1  female  38.0      1      0  71.2833   First  woman   
2           1       3  female  26.0      0      0   7.9250   Third  woman   
3           1       1  female  35.0      1      0  53.1000   First  woman   
4           0       3    male  35.0      0      0   8.0500   Third    man   
..        ...     ...     ...   ...    ...    ...      ...     ...    ...   
886         0       2    male  27.0      0      0  13.0000  Second    man   
887         1       1  female  19.0      0      0  30.0000   First  woman   
888         0       3  female   NaN      1      2  23.4500   Third  woman   
889         1       1    male  26.0      0      0  30.0000   First    man   
890         0       3    male  32.0      0      0   7.7500   Third    man   

     adult_male deck alive  alone  
0          True  NaN    no  False  
1         False    C   yes  False  
2         False  NaN   yes   True  
3         False    C   yes  False  
4          True  NaN    no   True  
..          ...  ...   ...    ...  
886        True  NaN    no   True  
887       False    B   yes   True  
888       False  NaN    no  False  
889        True    C   yes   True  
890        True  NaN    no   True  

[891 rows x 13 columns]

In [110]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [115]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'class',
       'who', 'adult_male', 'deck', 'alive', 'alone'],
      dtype='object')

In [116]:
df.info

<bound method DataFrame.info of      survived  pclass     sex   age  sibsp  parch     fare   class    who  \
0           0       3    male  22.0      1      0   7.2500   Third    man   
1           1       1  female  38.0      1      0  71.2833   First  woman   
2           1       3  female  26.0      0      0   7.9250   Third  woman   
3           1       1  female  35.0      1      0  53.1000   First  woman   
4           0       3    male  35.0      0      0   8.0500   Third    man   
..        ...     ...     ...   ...    ...    ...      ...     ...    ...   
886         0       2    male  27.0      0      0  13.0000  Second    man   
887         1       1  female  19.0      0      0  30.0000   First  woman   
888         0       3  female   NaN      1      2  23.4500   Third  woman   
889         1       1    male  26.0      0      0  30.0000   First    man   
890         0       3    male  32.0      0      0   7.7500   Third    man   

     adult_male deck alive  alone  
0      

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   survived    891 non-null    int64   
 1   pclass      891 non-null    int64   
 2   sex         891 non-null    object  
 3   age         714 non-null    float64 
 4   sibsp       891 non-null    int64   
 5   parch       891 non-null    int64   
 6   fare        891 non-null    float64 
 7   class       891 non-null    category
 8   who         891 non-null    object  
 9   adult_male  891 non-null    bool    
 10  deck        203 non-null    category
 11  alive       891 non-null    object  
 12  alone       891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(3)
memory usage: 66.7+ KB


In [126]:
dt=IterativeImputer(estimator=DecisionTreeRegressor())
df['age']=dt.fit_transform(df[['age']])
df

survived  pclass     sex        age  sibsp  parch     fare   class  \
0           0       3    male  22.000000      1      0   7.2500   Third   
1           1       1  female  38.000000      1      0  71.2833   First   
2           1       3  female  26.000000      0      0   7.9250   Third   
3           1       1  female  35.000000      1      0  53.1000   First   
4           0       3    male  35.000000      0      0   8.0500   Third   
..        ...     ...     ...        ...    ...    ...      ...     ...   
886         0       2    male  27.000000      0      0  13.0000  Second   
887         1       1  female  19.000000      0      0  30.0000   First   
888         0       3  female  29.699118      1      2  23.4500   Third   
889         1       1    male  26.000000      0      0  30.0000   First   
890         0       3    male  32.000000      0      0   7.7500   Third   

       who  adult_male deck alive  alone  
0      man        True  NaN    no  False  
1    woman       False    C   yes  False  
2    woman       False  NaN   yes   True  
3    woman       False    C   yes  False  
4      man        True  NaN    no   True  
..     ...         ...  ...   ...    ...  
886    man        True  NaN    no   True  
887  woman       False    B   yes   True  
888  woman       False  NaN    no  False  
889    man        True    C   yes   True  
890    man        True  NaN    no   True  

[891 rows x 13 columns]

In [132]:
kn=KNNImputer(n_neighbors=3)
df['age']=kn.fit_transform(df[['age']])
df

survived  pclass     sex        age  sibsp  parch     fare   class  \
0           0       3    male  22.000000      1      0   7.2500   Third   
1           1       1  female  38.000000      1      0  71.2833   First   
2           1       3  female  26.000000      0      0   7.9250   Third   
3           1       1  female  35.000000      1      0  53.1000   First   
4           0       3    male  35.000000      0      0   8.0500   Third   
..        ...     ...     ...        ...    ...    ...      ...     ...   
886         0       2    male  27.000000      0      0  13.0000  Second   
887         1       1  female  19.000000      0      0  30.0000   First   
888         0       3  female  29.699118      1      2  23.4500   Third   
889         1       1    male  26.000000      0      0  30.0000   First   
890         0       3    male  32.000000      0      0   7.7500   Third   

       who  adult_male deck alive  alone  
0      man        True  NaN    no  False  
1    woman       False    C   yes  False  
2    woman       False  NaN   yes   True  
3    woman       False    C   yes  False  
4      man        True  NaN    no   True  
..     ...         ...  ...   ...    ...  
886    man        True  NaN    no   True  
887  woman       False    B   yes   True  
888  woman       False  NaN    no  False  
889    man        True    C   yes   True  
890    man        True  NaN    no   True  

[891 rows x 13 columns]

In [131]:
age_m=df['age'].mean()
df['age']=df['age'].fillna(age_m)
df

survived  pclass     sex        age  sibsp  parch     fare   class  \
0           0       3    male  22.000000      1      0   7.2500   Third   
1           1       1  female  38.000000      1      0  71.2833   First   
2           1       3  female  26.000000      0      0   7.9250   Third   
3           1       1  female  35.000000      1      0  53.1000   First   
4           0       3    male  35.000000      0      0   8.0500   Third   
..        ...     ...     ...        ...    ...    ...      ...     ...   
886         0       2    male  27.000000      0      0  13.0000  Second   
887         1       1  female  19.000000      0      0  30.0000   First   
888         0       3  female  29.699118      1      2  23.4500   Third   
889         1       1    male  26.000000      0      0  30.0000   First   
890         0       3    male  32.000000      0      0   7.7500   Third   

       who  adult_male deck alive  alone  
0      man        True  NaN    no  False  
1    woman       False    C   yes  False  
2    woman       False  NaN   yes   True  
3    woman       False    C   yes  False  
4      man        True  NaN    no   True  
..     ...         ...  ...   ...    ...  
886    man        True  NaN    no   True  
887  woman       False    B   yes   True  
888  woman       False  NaN    no  False  
889    man        True    C   yes   True  
890    man        True  NaN    no   True  

[891 rows x 13 columns]